/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNINativeMemory */

#ifndef _Included_JNINativeMemory
#define _Included_JNINativeMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNINativeMemory
 * Method:    allocateMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNINativeMemory_allocateMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
